repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [--strict]
        files: \.(yaml|yml)$
  - repo: https://github.com/Open-Paws/no-animal-violence-pre-commit
    rev: v1.0.0
    hooks:
      - id: no-animal-violence
        files: \.(py|ts|js|md|yaml|yml)$
